openapi: 3.0.0
info:
  title: kytos/pathfinder
  version: v1
  description: "**Warning**: *This documentation is experimental and will
  change soon.*\n

  Keeps track of topology changes, and calculates the best path between two
  points."

paths:
  /api/kytos/pathfinder/v1/<source>/<destination>/<parameter>:
    get:
      summary: "Return a list of best paths between source and destination, in order."
      parameters:
        - in: path
          name: source
          description: "The source identifier. It may be a datapath or an interface. Examples:
                   '00:00:00:00:00:00:00:01:3', '00:00:00:00:00:00:00:02'."
          required: true
        - in: path
          name: destination
          description: "The destination identifier. It may be a datapath or an interface. Examples:
                   '00:00:00:00:00:00:00:01:3', '00:00:00:00:00:00:00:02'."
          required: true
        - in: path
          name: parameter
          type: string
          description: "The name of the parameter used to determine the best path.
          This parameter must be a custom property defined in the topology. Omitting
          this field will use the minimum number of hops as a parameter."
      responses:
        200:
          description: "Best paths calculated with success."
          content:
            application/json:
              schema:
                type: object
                properties:
                  paths:
                    type: array
                    items:
                      $ref: "#/components/schemas/Path"

components:
  schemas:
    Hop:
      type: string
      description: Hop identification. Usally is a `switch.id:interface.id`.
      example: 00:00:00:00:00:00:01:1

    Path:
      type: object
      description: Path between two points
      properties:
        hops:
          type: array
          description: Hops between two points
          items:
            $ref: "#/components/schemas/Hop"
          example:
            $ref: "#/examples/Hops"

examples:
  Hops:
    - 00:00:00:00:00:00:01:1
    - 00:00:00:00:00:00:01
    - 00:00:00:00:00:00:01:2
    - 00:00:00:00:00:00:02:1
    - 00:00:00:00:00:00:02
    - 00:00:00:00:00:00:02:2
