openapi: 3.0.0
info:
  title: kytos/pathfinder
  version: v1
  description: "**Warning**: *This documentation is experimental and will
  change soon.*\n

  Keeps track of topology changes, and calculates the best path between two
  points."

paths:
  /api/kytos/pathfinder/<source>/<destination>/:
    get:
      summary: "Return a list of paths between source and destination, sorted
      by the best path. For now, the best path is the minimum number of hops."
      parameters:
        - in: path
          name: source
          description: "The source identifier"
          required: true
          example: '00:00:00:00:01'
        - in: path
          name: destination
          description: "The destination identifier"
          required: true
          example: '00:00:00:00:02'
      responses:
        200:
          description: "Best paths calculated with success."
          content:
            application/json:
              schema:
                type: object
                properties:
                  paths:
                    type: array
                    items:
                      $ref: "#/components/schemas/Path"

components:
  schemas:
    Hop:
      type: string
      description: Hop identification. Usally is a `switch.id:interface.id`.
      example: 00:00:00:00:00:00:01:1

    Path:
      type: object
      description: Path between two points
      properties:
        hops:
          type: array
          description: Hops between two points
          items:
            $ref: "#/components/schemas/Hop"
          example:
            $ref: "#/examples/Hops"

examples:
  Hops:
    - 00:00:00:00:00:00:01:1
    - 00:00:00:00:00:00:02:1
    - 00:00:00:00:00:00:02
    - 00:00:00:00:00:00:02:2
    - 00:00:00:00:00:00:03:1
